package dev.loki.ask.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

//generated by https://materialkolor.com
//Color palette was taken here: https://coolors.co/palette/e63946-f1faee-a8dadc-457b9d-1d3557

internal val Primary = Color(0xFF1A1C1C)
internal val Constraint = Color(0xFFF3F3F4)
internal val OnError = Color(0xFFE5484D)
internal val OnPoint = Color(0xFF1ffba08)

internal val FireGradient: Brush = Brush.verticalGradient(
    colors = listOf(
        Color(0xFFBC0000),
        Color(0xFFBC0000).copy(alpha = 0.8f)
    )
)